name: Update Submodule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # 1時間おき

permissions:
  contents: write

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 #v3.2.0
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}


      - name: Configure git to use token for GitHub
        run: git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/".insteadOf "git@github.com:"

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          submodules: recursive
          token: ${{ steps.app-token.outputs.token }}

      - name: Update Submodule
        run: git submodule update --init --recursive

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: update submodule"
          git push

